# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /lesson_1

# Copy the current directory contents into the container at /app
COPY . /lesson_1

# Run app.py when the container launches
CMD ["python", "app.py"]